micronaut:
  application:
    name: progimage-storage
  server:
    port: 10001
    multipart:
      max-file-size: 10MB
endpoints:
  info:
    enabled: true
    sensitive: false
  health:
    enabled: true
    sensitive: false
    details-visible: anonymous
progimage:
  storage-dir: /var/tmp/progimage/
  cache-dir: /var/tmp/progimage-cache/
